import { Game } from "../shared/models/api";

export const gameModel: Game = {
  _id: "z",
  user: "1",
  audience: "none",
  authors: ["none"],
  description: "none",
  knowledgeField: "none",
  simplyGameplay: "none",
  maxNumberPlayers: 3,
  minNumberPlayers: 3,
  name: "none",
  requirements: "none",
  decks: [],
  roles: [],
  tokens: [],
  states: [
    {
      _id: "1",
      label: "Game Start",
      conditionalRule: null,
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [],
      transition: "Game start configuration",
    },
    {
      _id: "2",
      label: "Game start configuration",
      conditionalRule: null,
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [
        {
          _id: "a",
          label: "st rule 1",
          simplerDescription: "all players draw 5 cards from game deck",
        },
        {
          _id: "a",
          label: "st rule 2",
          simplerDescription: "chose random player to start",
        },
      ],
      transition: "Turn setup",
    },
    {
      _id: "3",
      label: "Turn setup",
      conditionalRule: {
        _id: "b",
        label: "Choose next play",
        conditions: [
          {
            test: "the player of the turn has no challenge impediments",
            effectIfTrue: {
              simpleEffect: "S/he can choose to play a challenge",
            },
            stateIfTrue: "Play a challenge",
          },
        ],
        failureCondition: {
          test: "can't do any play",
          effectIfTrue: {
            simpleEffect: "next player",
          },
          stateIfTrue: "Turn setup",
        },
      },
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [
        {
          _id: "c",
          label: "rule 6",
          simplerDescription: "the player of the turn draws 1 card from game deck",
        },
        {
          _id: "d",
          label: "rule 5",
          simplerDescription: "the table is filled with 5 challenge cards, if not already",
        },
      ],
      transition: null,
    },
    {
      _id: "4",
      label: "Play a challenge",
      conditionalRule: {
        _id: "e",
        label: "play a challenge",
        conditions: [
          {
            test: "the player used a game card that answers correctly the challenge card that s/he chose from table",
            effectIfTrue: {
              simpleEffect: "S/he wins the challenge",
            },
            stateIfTrue: "Update status: success",
          },
        ],
        failureCondition: {
          test: "the player used a game card that DO NOT answers correctly the challenge",
          effectIfTrue: {
            simpleEffect: "S/he loose the challenge",
          },
          stateIfTrue: "Update status: failure",
        },
      },
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [
        {
          _id: "f",
          label: "rule 7",
          simplerDescription: "the player of the turn draws 1 card from game deck",
        },
        {
          _id: "g",
          label: "rule 8",
          simplerDescription: "the table is filled with 5 challenge cards, if not already",
        },
      ],
      transition: null,
    },
    {
      _id: "5",
      label: "Update status: success",
      conditionalRule: null,
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [
        {
          _id: "h",
          label: "st rule 3",
          simplerDescription: "the player earns +1 victory point",
        },
      ],
      transition: "Check if game completed",
    },
    {
      _id: "6",
      label: "Update status: failure",
      conditionalRule: null,
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [
        {
          _id: "i",
          label: "rule",
          simplerDescription: "there is no penalties for loosing",
        },
      ],
      transition: "Check if game completed",
    },
    {
      _id: "7",
      label: "Check if game completed",
      conditionalRule: {
        _id: "j",
        label: "end game condition",
        conditions: [
          {
            test: "any player achieved 5 victory points",
            effectIfTrue: {
              simpleEffect: "S/he wins the game",
            },
            stateIfTrue: "Game over",
          },
        ],
        failureCondition: {
          test: "no player achieved 5 victory points yet",
          effectIfTrue: {
            simpleEffect: "next player",
          },
          stateIfTrue: "Play again or next player",
        },
      },
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [],
      transition: null,
    },
    {
      _id: "8",
      label: "Play again or next player",
      conditionalRule: {
        _id: "k",
        label: "play again",
        conditions: [
          {
            test: "not all play possibilities were used",
            effectIfTrue: {
              simpleEffect: "S/he wins the game",
            },
            stateIfTrue: "Game over",
          },
        ],
        failureCondition: {
          test: "no player achieved 5 victory points yet",
          effectIfTrue: {
            simpleEffect: "next player",
          },
          stateIfTrue: "Play again or next player",
        },
      },
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [],
      transition: null,
    },
    {
      _id: "-1",
      label: "Game Over",
      conditionalRule: null,
      color: "#dedede",
      game: "z",
      purpose: "start",
      height: 120,
      width: 120,
      x: 10,
      y: 10,
      statementRules: [],
      transition: null,
    },
  ],
};
